# This Cloud Build configuration file runs 'terraform plan' to preview infrastructure changes.
#
# To run this build, you would typically use a gcloud command like:
# gcloud builds submit --config cloudbuild.yaml .
#
# Prerequisites:
# 1. Your Terraform code (.tf files) should be in the same directory as this file.
# 2. The Cloud Build service account needs appropriate IAM permissions (e.g., roles/iam.serviceAccountUser
#    and any roles needed to read the state of the resources you're managing).

steps:
  # 1. Initialize Terraform
  # This step downloads the necessary provider plugins and sets up the backend.
  - name: 'hashicorp/terraform:1.5.7'
    entrypoint: 'terraform'
    args: ['init']
    id: 'Terraform Init'
    dir: '2-cloud-build-triggers'

  # 2. Validate Terraform Configuration
  # This step checks for syntax errors and ensures the configuration is internally consistent.
  - name: 'hashicorp/terraform:1.5.7'
    entrypoint: 'terraform'
    args: ['validate']
    id: 'Terraform Validate'
    dir: '2-cloud-build-triggers'

  # 3. Generate Terraform Plan
  # This step creates an execution plan and saves it to a file named 'tfplan'.
  # The GCP Project ID is passed in via a substitution variable.
  # You can replace '-var-file' or add more '-var' arguments as needed.
  - name: 'hashicorp/terraform:1.5.7'
    entrypoint: 'terraform'
    args:
      - 'plan'
      - '-out=tfplan'
      # Example of using a substitution for project_id.
      # When you run the build, Cloud Build automatically populates $PROJECT_ID.
      - '-var=project_id=${PROJECT_ID}'
    id: 'Terraform Plan'
    dir: '2-cloud-build-triggers'

# Save the generated plan file as an artifact.
# This allows you to inspect the plan after the build completes or use it
# in a subsequent 'apply' build.
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/artifacts'
    paths: ['tfplan']

# Explicitly define where to store the logs for this build.
# This is required when using a custom service account.
logsBucket: 'gs://${PROJECT_ID}_cloudbuild/artifacts/logs'