apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
  name: marketplace-tools-display
spec:
  ui:
    input:
      booleanGroups:
      - name: cloud_platform_api_access
        title: Google Cloud Platform API
      sections:
      - name: boot_disk
        title: Boot Disk
        tooltip: Each instance requires a disk to boot from.
      - name: networking
        title: Networking
      - name: api_access
        title: API Access
        tooltip: Applications running on the VM can call Google Cloud APIs. Select
          the API access you want to allow. <a href="https://cloud.google.com/compute/docs/authentication">Learn
          more</a>
      variables:
        accelerator_count:
          min: 1
          name: accelerator_count
          title: GPU Count
          xGoogleProperty:
            gceGpuCount:
              machineTypeVariable: machine_type
            type: ET_GCE_GPU_COUNT
        accelerator_type:
          name: accelerator_type
          title: GPUs
          xGoogleProperty:
            gceGpuType:
              gpuType:
              - nvidia-tesla-p100-vws
              - nvidia-tesla-p4-vws
              - nvidia-tesla-t4-vws
              - nvidia-l4-vws
              - nvidia-l4
              - nvidia-tesla-v100
              machineType: machine_type
            type: ET_GCE_GPU_TYPE
        boot_disk_size:
          max: 10000
          name: boot_disk_size
          section: boot_disk
          title: Boot disk size in GB
          xGoogleProperty:
            gceDiskSize:
              diskTypeVariable: boot_disk_type
            type: ET_GCE_DISK_SIZE
        boot_disk_type:
          name: boot_disk_type
          section: boot_disk
          title: Boot disk type
          xGoogleProperty:
            type: ET_GCE_DISK_TYPE
            zoneProperty: zone
        enable_cloud_api:
          booleanGroup: cloud_platform_api_access
          name: enable_cloud_api
          section: api_access
          title: Allow full access to all of Google Cloud Platform APIs on the VM
        external_ips:
          maxItems: 1
          minItems: 1
          name: external_ips
          section: networking
          title: External IP
          tooltip: An external IP address associated with this instance. Selecting
            "None" will result in the instance having no external internet access.
            <a href="https://cloud.google.com/compute/docs/configure-instance-ip-addresses">Learn
            more</a>
          xGoogleProperty:
            gceExternalIp:
              allowStaticIps: true
              networkVariable: networks
              notConfigurable: false
            type: ET_GCE_EXTERNAL_IP
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Goog Cm Deployment Name
        machine_type:
          name: machine_type
          title: Machine type
          xGoogleProperty:
            gceMachineType:
              minCpu: 4
              minRamGb: 16
            type: ET_GCE_MACHINE_TYPE
            zoneProperty: zone
        networks:
          maxItems: 1
          minItems: 1
          name: networks
          section: networking
          title: Network name
          xGoogleProperty:
            gceNetwork:
              allowSharedVpcs: true
              machineTypeVariable: machine_type
            type: ET_GCE_NETWORK
        project_id:
          invisible: true
          name: project_id
          title: Project Id
        source_image:
          enumValueLabels:
          - label: nv-windows-server-2022-vws-581-42-v202510290321
            value: projects/mpi-nvidia-vgpu-public/global/images/nv-windows-server-2022-vws-581-42-v202510290321
          name: source_image
          title: Image version
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
        sub_networks:
          maxItems: 1
          minItems: 1
          name: subnetworks
          section: networking
          title: Subnetwork name
          xGoogleProperty:
            gceSubnetwork:
              networkVariable: networks
            type: ET_GCE_SUBNETWORK
            zoneProperty: zone
        zone:
          name: zone
          subtext: GPU availability is limited to certain zones. <a href="https://cloud.google.com/compute/docs/gpus">Learn
            more</a>
          title: Zone
          xGoogleProperty:
            type: ET_GCE_ZONE
